// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/edg-branding/Bold.tsx": () => import("../components/mockups/edg-branding/Bold.tsx"),
  "./components/mockups/edg-branding/Clinical.tsx": () => import("../components/mockups/edg-branding/Clinical.tsx"),
  "./components/mockups/edg-branding/Editorial.tsx": () => import("../components/mockups/edg-branding/Editorial.tsx"),
  "./components/mockups/edg-fonts/Inter.tsx": () => import("../components/mockups/edg-fonts/Inter.tsx"),
  "./components/mockups/edg-fonts/JakartaSans.tsx": () => import("../components/mockups/edg-fonts/JakartaSans.tsx"),
  "./components/mockups/edg-fonts/SerifEditorial.tsx": () => import("../components/mockups/edg-fonts/SerifEditorial.tsx")
};
